- name: tower
  hosts: web
  tasks:
      - name: install ftp
        yum:
            name: vsftpd
            state: installed  
      - name: install samba
        yum:
            name: samba
            state: installed  
